########## DIFFUSION ##########

seed: 42
device: cuda

# Experiment (ks, kolmogorov)
exp_dir: kolmogorov/Re90
input_dim: 2
output_dim: 2
n_dim: 2
domain_size:
  - 1
  - 1
ratio: 1
k_max_x: 12
k_max_y: 12
l: 1

# Model parameters
n_fourier_layer: 3
width: 32
hidden_proj: 64
mlp: true
layers_mlp: [32,64,32]
timesteps: 1000
class_mlp_layers: [64,128,1000]
noise_sampling_coeff: 0.3


# Training parameters
num_epochs: 500
seq_length: 5
batch_size: 128
num_workers: 2
loss_score: mse 
loss_cat: cross_entropy
optimizer: 
  type: adam
  lr: 0.0001
  wd: 100.
scheduler:
  name: cosine_annealing
  T_max: 500
  eta_min: 0.00001


lambda_c: 0.3
stride: 5
ds: 2


#
exp_name: diffusion1
name_weigths_to_load: null