########### EMULATOR #############
seed: 42
device: cuda

# Experiment (ks, kolmogorov)
exp_dir: kolmogorov/Re90
input_dim: 2
output_dim: 2
n_dim: 2
domain_size:
  - 1
  - 1
ratio: 1
res: 64

# Model parameters
width: 32
level: 3
layers: 4
#wavelet:
#  - near_sym_b
#  - qshift_b 
wavelet: db4
mode: periodization
padding: 0
tau: 0.00001
timesteps: 1000
class_mlp_layers: [64,128,1000]
noise_sampling_coeff: 0.3

# Training parameters
num_epochs: 500
seq_length: 5
batch_size: 128
num_workers: 2
loss_score: mse 
loss_cat: cross_entropy
optimizer: 
  type: adam
  lr: 0.0005
  wd: 100.
scheduler:
  name: cosine_annealing
  T_max: 500
  eta_min: 0.00001
metrics:
  - rmse
  - mae
  - relative_rmse # relative rmse
  - relative_mae # relative l1 norm

lambda_c: 0.3
stride: 5
ds: 2

#Early stopping
patience: 10
min_delta: 0.00000001

#
exp_name: wno_diff_lvl3_db4_period_mse_width32
name_weights_to_load: null
